AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: HomeHarbor Serverless API

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: nodejs18.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        PROPERTIES_TABLE: !Ref PropertiesTable
        AI_INSIGHTS_TABLE: !Ref AiInsightsTable
        IMAGES_BUCKET: !Ref ImagesBucket
        OPENROUTER_SECRET_ARN: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:home-harbor/openrouter

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        AllowHeaders:
          - content-type
      StageName: prod
      DefaultRouteSettings:
        ThrottlingBurstLimit: 10
        ThrottlingRateLimit: 100

  PropertiesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: properties-socrata.handler
      # No DynamoDB needed - queries CT Open Data Portal directly
      Timeout: 15  # Allow time for Socrata API calls
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /properties
            Method: GET

  CitiesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: properties-socrata.citiesHandler
      Timeout: 10
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /cities
            Method: GET

  MetadataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: properties-socrata.metadataHandler
      Timeout: 15
      Description: Returns dataset metadata (cities, price ranges, property types)
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /metadata
            Method: GET

  # SearchFunction - deprecated, now using PropertiesFunction with filters
  # Keeping for backwards compatibility but redirecting to properties-socrata

  AnalyzeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: analyze.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AiInsightsTable
        - S3ReadPolicy:
            BucketName: !Ref ImagesBucket
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:home-harbor/openrouter-*
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /analyze
            Method: POST

  DescribeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: describe.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AiInsightsTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:home-harbor/openrouter-*
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /describe
            Method: POST

  ChatFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: chat.handler
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:home-harbor/openrouter-*
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /chat
            Method: POST

  PropertiesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: home-harbor-properties-dev
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  AiInsightsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: home-harbor-ai-insights-dev
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  ImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: home-harbor-images-dev

  # Note: Secrets Manager secret 'home-harbor-secrets-dev' is created manually
  # and should contain: {"openrouter_api_key": "sk-or-v1-..."}
  # Reference it in Lambda policies via SECRETS_NAME env var

Outputs:
  ApiUrl:
    Description: API Gateway URL
    Value: !Sub https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/prod